### PR TITLE
10167 Safely manage pointers in Swift

### PR DESCRIPTION
**Pull request by dasautoooo**
Welcome to the unsafe swift squad again!
It's also a tough session, might take longer to finish.

### CODE REVIEW

**Comment by zntfdr** [comment]
Wow, this session is packed 🤯

**Comment by dasautoooo** [comment]
I tried to keep the note as succinct as possible, but this is a long and compact session. It's inevitable for me to miss some important takeaways. Please feel free to add things to it, adjust words is also welcome.

Don't forget to add your name to the contributors. 😁

**Comment by dasautoooo** [comment]
This is an amazing session, I think it's one of my favorite this year. Each topic in this session can be expanded to an article, maybe it can be a chapter in a book.

The biggest takeaway is to appreciate how safe Swift language is if you're not a member of the unsafe swift squad ☺️. By learning and understanding the pointer implementation in Swift, really gives you an insight on how to use pointers safely not only in Swift but also in other languages. 

Wanna do some **unsafe** experiments to explore the **unsafe** Swift right away. 😁

**Comment by zntfdr** [comment]
This is also a session that I'll be watching soon, happy to add even more notes if needed 👍🏻😊

**Pull request merged**
