### PR TITLE
Add session 10097 Advances in UICollectionView.

### PR DESCRIPTION
**Pull request by dasautoooo**
Will add related session notes later once those done.

### CODE REVIEW

**Comment by zntfdr** [comment]
Thank you @dasautoooo! Is this PR ready to be merged?

**Comment by zntfdr** [comment]
Awesome, thank you! Will merge in a few hours after work 🙏

**Comment by dasautoooo** [comment]
Add a note for session 10045 Advances in diffable data sources.

**Comment by zntfdr** [comment]
Thank you so much @dasautoooo!

**Pull request merged**
